services:
  dbservice:
    image: mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=sms
      
    healthcheck: 
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 1s
     timeout: 3s
     retries: 10
     
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306

    networks:
      - boot-mysql-net

  appservice:
    build: ./target
    
    "depends_on": {
      "dbservice": {
        "condition": service_healthy
        }
     }
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/sms?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      
    ports:
      - 8080:8080

    networks:
      - boot-mysql-net

networks:
  boot-mysql-net:
    driver: bridge
