version: "3"
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Guruji123$$
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=sms
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306

    networks:
      - boot-mysql-net

  appservice:
    build: ./target
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/sms?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=Guruji123$$
    ports:
      - 8081:8080

    networks:
      - boot-mysql-net

networks:
  boot-mysql-net:
    driver: bridge
